### PR TITLE
Async query and other changes

### PR DESCRIPTION
**Pull request by TonyValenti**
Hi @robertvazan -
The attached PR represents the changes.

There may seem to be a lot of changes but that is only because of a few things:
1. Documentation updated to latest syntax
2. Some code split into multiple files (ie.  NtpClient_Static.cs, NtpClient_Sync.cs, NtpClient_Async.cs).

The attached PRs allow the code to be used as follows:
For Sync:
```
//This will issue a new sync request
var CorrectionPacket = NtpClient.Default.GetCorrectionResponse();
//This will issue a new sync request
var CorrectionOffset = NtpClient.Default.GetCorrectionOffset();

//This will retrieve the last cached result:
var LastCorrection = NtpClient.Default.LastCorrectionOffset;
```

For Async:
```
//This will issue a new async request
var CorrectionPacket = await NtpClient.Default.GetCorrectionResponseAsync();
//This will issue a new async request
var CorrectionOffset = await NtpClient.Default.GetCorrectionOffsetAsync();

//This will retrieve the last cached result:
var LastCorrection = NtpClient.Default.LastCorrectionOffset;
```

The common ```Now + LastCorrectionOffset``` math is also available through:
```
var V1 = NtpClient.Default.DateTimeNow;
var V2 = NtpClient.Default.DateTimeUtcNow;
var V3 = NtpClient.Default.DateTimeOffsetNow;
var V4 = NtpClient.Default.DateTimeOffsetUtcNow;
```

### CODE REVIEW

**Comment by TonyValenti** [comment]
Hi @robertvazan -
I just wanted to follow up.  Does the PR look good to you?

**Comment by robertvazan** [comment]
@TonyValenti It's good, but it needs some changes. I am considering merging it as is, improving upon your work, and then releasing. I need one afternoon for this. Please be patient. It's in my TODO toplist.

**Comment by TonyValenti** [comment]
@robertvazan - That sounds great!  I just wanted to make sure it wasn't forgotten.

If you're up for a more "drastic" change, would you be OK if I made the packet a record instead of a class?

**Comment by robertvazan** [comment]
@TonyValenti Packet feels like it needs redesign, but this is not it. Records are intended to be immutable while packet seems to be better off with create-then-edit API.

**Comment by robertvazan** [comment]
I have merged this PR as is, but I will make further changes before release.

**Comment by TonyValenti** [comment]
Sounds great!  Looking forward to your enhancements!

**Comment by robertvazan** [comment]
@TonyValenti I have made my changes. Please check the library will work for you. I will make 3.0 release in a few days.

**Pull request merged**
